### PR TITLE
Add VirtualButton to replace buttons in banks

### PR DESCRIPTION
**Pull request by jypma**
The current push button implementations for 1,2,3 and 6 (ladder) buttons are very different from one another, leading to inconsistent and hard to understand usage of multi-button "pedals".

This PR introduces the concept of "virtual" buttons as a new layer. Pedals only define how many actual buttons are connected to the pedal in what electrical configuration (1, 2, 3, ladder). What each individual button does, and in what mode, can be configured for each physical button, independently. A new user interface (and storage) for that was created, called "Virtual Buttons". Since the storage is a fair bit larger than the current "banks" storage, it's saved on SPIFF instead of NVS.

In order to test it out, configure a (button) pedal as "Virtual Button" on the Pedals page. After that, you can configure the actual buttons under the "Virtual Buttons" tab.

New features:
- Separate physical buttons of 1 pedal can be configured completely independently, with a (hopefully) intuitive UI.
- For up/down-style buttons (MIDI CC, MIDI Program, ...) the last-known CC and program is remembered centrally for each channel. This allows a "soft take-over" when switching banks, or even when externally triggered.
- The virtual button configuration can be downloaded and uploaded via REST.

This PR is just a first "draft", please let me know what you think :-) 

Still missing:
- [ ] Implement double and long click 
- [ ] Update internal state in oncoming MIDI CC / Program, for "soft takeover"
- [ ] Extend "soft takeover" into analog pedal behaviour

### CODE REVIEW

**Comment by alf45tar** [comment]
Thanks for your PR.
It looks very interesting.

**Comment by jypma** [comment]
Thanks! I do realize that it moves in a new direction on several fronts (e.g. the UI html DSL), combining several ideas that I had; please do let me know your thoughts on strategies to potentially split it up into several PRs.

**Comment by alf45tar** [comment]
I suggest to create a separate branch for working on the new version including you improving

**Comment by alf45tar** [comment]
I created a new branch called dev-2.0 for implementing your ideas and improvements.
I would like to replace the current bank configuration with the virtual button configuration. For each bank should be possible to add a certain number of events and the corresponding actions.

**Comment by jypma** [comment]
I will! Can't promise anything on timelines though.

Do you have a particular suggestion on how to slice it up? I'm thinking I could start with a smaller "setup" PR that splits up the current `Pedalino.h` into definitions and declarations, and maybe move the global variables into a `.cpp` file instead. That would make the rest of the code a bit cleaner.

**Comment by alf45tar** [comment]
Take your time and feel free to modify everything. You are a better programmer than me.

**Comment by alf45tar** [comment]
"Virtual" button implemented in the new version just released

**Pull request closed without merging**
